### ISSUE TITLE
Starting funds are lumped into money gained

### ISSUE THREAD

**Issue by Sedohr** [zinic/crawl#10]
In this example, "funds gained" also includes the funds in starting money instead of purely money gained. (this character also has affluent at a custom value, hence the amount)

Monetary Funds
Starting Funds: $$ 1500
Funds Gained: $$ 4500
Funds Spent: $$ 3200
Funds Available: $$ 1300

```
---

character:
  name: Basic Hunter 1
  aspect_points: 128
  starting_funds: 1500

  wallet:
    spent:

    recieved:
      # You may specify spent amounts
      - 1000

  aspects:
    - name: Hunter Armory
      text: The hunter has had access to a large military grade armory at some point.
      rules:
       Starting Wealth Modifier: $$ 2000
```
