### ISSUE TITLE
Great Slash does not pull mobility modifiers, and gives -1 not -2

### ISSUE THREAD

**Issue by Sedohr** [zinic/crawl#13]
As the title states when you put great slash on a character it has a -1 modifier instead of -2, and does not calculate mobility bonuses. Looking at the aspect itself it shows -1 not -2 in the rules, while the description says -2 so this may be just a typo. 

In the code below the character has +3 Mobility so the net roll should be +1 on Great Slash. I am adding the output below the code as well.
```
---

character:
  name: x 
  aspect_points: 278
  starting_funds: 2000

  items:
    - name: 1t3m

  aspects:
    - name: Fit
    - name: Slash
    - name: Great Slash
    - name: Intense Acrobatic Training

    - name: x Resistance Training
      text: x
      requires:
        - Intense Resistance Training
        - Fit
      rules:
        - name: Core Aspect Modifier
          option: "+2"
          modifies:
          - Mobility
```

output
```
Great Slash

    Difficulty 8
    Modifier: -1
```
