### ISSUE TITLE
Leaping Strike does not pull from any core aspect

### ISSUE THREAD

**Issue by Sedohr** [zinic/crawl#14]
As stated when adding "Leaping Strike" into your character it does not pull from either strength or mobility. It appears it should pull from the respective Core aspect based on the attack it is replacing according to the description, which means it could be strength or mobility.

```
character:
  name: creature
  aspect_points: 203
  starting_funds: 0

  aspects:
    - name: Grapple   
    - name: Fit
    - name: Intense Acrobatic Training
    - name: Intense Resistance Training
    - name: Leaping Strike
```

Outputs

```
Leaping Strike

    Difficulty 8
    Modifier: +1
```
