### ISSUE TITLE
Percerption does not pull Intelligence Modifiers

### ISSUE THREAD

**Issue by Sedohr** [zinic/crawl#2]
In this example the character has +1 intelligence, but Perception is not showing this modifier. In this example I also added another aspect that does full from intelligence and is shown to be working correctly to verify the intelligence modifier is being added.

Skill Stats

    Intelligence
        Difficulty: GM Specified
        Modifier: +1
    Knowledge - Arcane
        Difficulty 8
        Modifier: +1
    Mobility
        Difficulty: GM Specified
        Modifier: 0
    Perception
        Difficulty 8
        Modifier: 0
    Strength
        Difficulty: GM Specified
        Modifier: 0

Code below.
```
---

character:
  name: Basic Cabalist 1
  aspect_points: 132
  starting_funds: 1000

  items:
    - name: Making a character
  aspects:
    - name: Mental Endurance
    - name: Mentat
    - name: Knowledge - Arcane
    - name: Perception
```
