### ISSUE TITLE
Output breaks, "Skill dependency tree broken"

### ISSUE THREAD

**Issue by Sedohr** [zinic/crawl#3]
*Please note the details in this character are potentially meta to the game. I wouldn't have posted the details unless it was required for this bug. *

I tried to isolate what specifically caused this, but the most I could get is it's some combination of aspects in this character. I thought it was only Grapple at first, but Grapple alone didn't cause the issue. I thought it might be Perception and Grapple causing a conflict as well, since that's when I was able to get it to trigger a few times. If I just put up those two (and fit since it's needed for grapple) it did not happen though. I ran through some other iteration tests and even without grapple it sometimes happens so I'm really not sure exactly what is causing it other than some form of combination of aspects.

Code below.
```
---

character:
  name: Meta Name
  aspect_points: 200
  starting_funds: 0

  items:
    - name: Let me build a character
  aspects:
    - name: Adonic
    - name: Grapple
    - name: Fit
    - name: Duck and Dodge
    - name: Dive for Cover
    - name: Intense Acrobatic Training
    - name: Intense Endurance Training
    - name: Intense Resistance Training
    - name: Perception
    - name: Keen Senses
    - name: Leaping Strike
    - name: Martial Artist
    - name: Pivot and Roll
    - name: Quiet Steps
    - name: Slash
    - name: Survival
    - name: Trap Finder
    - name: Vigor

```
