### ISSUE TITLE
Items providing skills do not appear in aspect list

### ISSUE THREAD

**Issue by Sedohr** [zinic/crawl#5]
When creating an item that provides an aspect (such as firebolt), this aspect does not appear in your list of aspects or Skill Stats for quick reference. (unsure if this is intentional since it's an item and not a true aspect on the character.

Example code below

```
---

character:
  name: Basic Cabalist 1
  aspect_points: 105
  starting_funds: 1000

  items:
    - name: Simple Infused Focus Item
      text: A basic focus item, but it also provides an attack. Type Differs per cabalist (kinetic/cold/fire/electric/meta)
      grants:
       - Firebolt
      rules:
       Accuracy Modifier: +1 Attack Accuracy
       Magic: Magic

    - name: Basic Cabalist Rags
      text: An armor piece quickly patched together and infused with magic, to mitigate concussive damage.
      rules:
       Damage Resistance: +2 DR
      wearable:
       slot: Torso
  aspects:
    - name: Fit
    - name: Duck and Dodge
    - name: Intense Acrobatic Training
    - name: Intense Endurance Training
    - name: Perception
    - name: Keen Senses
    - name: Survival
    - name: Vigor
    - name: Mental Endurance
    - name: Knowledge - Arcane
    - name: Mentat
    - name: Affluent
    - name: Affluent
    - name: Spell Dart
```
