### ISSUE TITLE
Applying 2+ core aspect modifiers costs as a sum of both

### ISSUE THREAD

**Issue by malconis** [zinic/crawl#7]
If an aspect modifies two core aspects, the cost of the second aspect does not start a new Fibonacci sequence, but rather it continues from the first.
```
Custom Aspect  
       - name: Core Aspect Modifier
           option: "+2"
           modifies:
             - Strength
         - name: Core Aspect Modifier
           option: "+1"
           modifies:
             - Mobility


Equals
         - name: Core Aspect Modifier
           option: "+3"
           modifies:
             - Strength
```
