### ISSUE TITLE
"grants a skill but is missing the required rules: Energy Point Cost"

### ISSUE THREAD

**Issue by Sedohr** [zinic/crawl#9]
When adding certain skills it provides the error "grants a skill but is missing the required rules: Energy Point Cost"

In the example I will post below this error is given,

General Error
Aspect Lockpicking grants a skill but is missing the required rules: Energy Point Cost
Aspect Survival grants a skill but is missing the required rules: Energy Point Cost

code
```
---

character:
  name: Basic Hunter 1
  aspect_points: 134
  starting_funds: 1000

  items:
  aspects:
    - name: Fit
    - name: Duck and Dodge
    - name: Intense Acrobatic Training
    - name: Intense Resistance Training
    - name: Perception
    - name: Keen Senses
    - name: Survival
    - name: Vigor
    - name: Quiet Steps
    - name: Mental Endurance
    - name: Knowledge - Survival
    - name: Mentat
    - name: Lockpicking
    - name: High Manual Dexterity
```
